apiVersion: v1
kind: Service

metadata:
  name: kbnt-api-service

spec:
  type: NodePort

  selector:
    app: kbnt-api

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080